<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_Unnatural</name>
   <tag></tag>
   <elementGuidId>740ec288-fe3f-40f1-be8c-e7cf02b66a84</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unnatural</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Death-step1&quot;)/div[@class=&quot;controls&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-info psDeathType&quot;]/strong[1]</value>
   </webElementProperties>
</WebElementEntity>
